baseURL = "https://blog.chengjf.com/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Chengjf"
copyright = "This is a chengjf's blog."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableGitalk = false
enableGiscus = true


# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="chengjf/discussion.blog.chengjf.com"
    data_repo-id="R_kgDOK69LoQ"
    data_category="Announcements"
    data_category-id="DIC_kwDOK69Loc4Cb06P"
    data_mapping="og:title"
    data_strict="0"
    data_reactions-enabled="1"
    data_emit-metadata="0"
    data_input-position="top"
    data_theme="preferred_color_scheme"
    data_lang="zh-CN"
    crossorigin="anonymous"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/posts"
name = "博文"
weight = 1
